### ISSUE TITLE
colcon build failing

### ISSUE THREAD

**Issue by Bggopal** [noshluk2/ROS2-Raspberry-PI-Intelligent-Vision-Robot#1]
hi @noshluk2 ,

While trying to build the repo, using colcon build, it fails, with an error

```
Starting >>> vision_rpi_bot
--- stderr: vision_rpi_bot                   
error: can't copy 'resource/vision_rpi_bot': doesn't exist or not a regular file
---
Failed   <<< vision_rpi_bot [5.10s, exited with code 1]

Summary: 0 packages finished [9.22s]
  1 package failed: vision_rpi_bot
  1 package had stderr output: vision_rpi_bot

```
what would be the cause

**Comment by noshluk2** [comment]
provide your setup.cfg file with package directory

**Comment by Bggopal** [comment]
hi @noshluk2 

this is my folder structure, inside the workspace is the  src/

![image](https://user-images.githubusercontent.com/59637425/235342308-5311e09d-e576-48f4-ad97-2161ab02cf6a.png)

my setup.cfg is 
```
[develop]
script-dir=$base/lib/vision_rpi_bot
[install]
install-scripts=$base/lib/vision_rpi_bot
```

still i am getting the same error

**Comment by Bggopal** [comment]
hi @noshluk2 

i solved the issue, the file in the resource was missing, i solved with creating a empty file with same name as package inside the resource directory.
then colcon build succeeded

**Comment by noshluk2** [comment]
That is great , it was written in the error missing file (y)

**Comment by Bggopal** [comment]
hi @noshluk2 

thanks for noticing, i think you can add that file (vision_rpi_bot) inside the resource folder, in your git repo, as it is still missing. Thanks for your work.

**Comment by noshluk2** [comment]
@Bggopal  kindly do a pull request i will review it and add into this repository
